
version: "3.8"

services:

  mftp:
    build:
      context: ./mftp
      dockerfile: Dockerfile
    image: proffapt/mftp
    container_name: mftp
    restart: unless-stopped
    command: $MFTP_MODE
    volumes:
      - $MFTP_CONFIG/env.py:/mftp/env.py
      - $MFTP_CONFIG/token.json:/mftp/token.json 
      - $MFTP_CONFIG/credentials.json:/mftp/credentials.json
      - $MFTP_CONFIG/mail_send_token.json:/mftp/mail_send_token.json
      - $MFTP_CONFIG/mail_send_creds.json:/mftp/mail_send_creds.json
      - $MFTP_CONFIG/.lsnif:/mftp/.lsnif
      - $MFTP_CONFIG/.session:/mftp/.session