name: Ping
on:
  schedule:
    - cron: '0/10 * * * *'
jobs:
  build:
    name: ping heroku server
    runs-on: ubuntu-latest  
    steps:
      - name: cURL request
        run: curl mftp.herokuapp.com -o NUL